make run:
	cargo run

# checks whether codebase complies without creating an executable
make check:
	cargo check

make compile_run:
	cargo build ;\
	./target/debug/hello_cargo

make prod:
	cargo build --release ;\
	./target/release/hello_cargo